# permissions for end users to view atonixcorps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: atonixcorp-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: atonixcorp-operator
    app.kubernetes.io/part-of: atonixcorp-operator
    app.kubernetes.io/managed-by: kustomize
  name: atonixcorp-viewer-role
rules:
- apiGroups:
  - cache.atonixcorp.org
  resources:
  - atonixcorps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.atonixcorp.org
  resources:
  - atonixcorps/status
  verbs:
  - get
