apiVersion: v1
kind: Namespace
metadata:
  name: atonixcorpvm
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quetzal
  namespace: atonixcorpvm
  labels:
    app: quetzal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quetzal
  template:
    metadata:
      labels:
        app: quetzal
    spec:
      imagePullSecrets:
      - name: ofidohubvm-pull-secret
      containers:
      - name: atonixcorpvm
        image: ofidohubvm/quetzal:latest
        ports:
        - containerPort: 59876
        env:
        - name: DB_HOST
          value: "atonixcorpvm-postgresql"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: "atonixdevmaster"
        - name: DB_PASSWORD
          value: "sf9x7ha2tcinn"
        - name: DB_NAME
          value: "atonixcorpk8sdb"
---
apiVersion: v1
kind: Service
metadata:
  name: quetzal-service
  namespace: atonixcorpvm
spec:
  selector:
    app: quetzal
  ports:
  - name: http
    protocol: TCP
    port: 59876
    targetPort: 59876
  - name: jupyter
    protocol: TCP
    port: 8888
    targetPort: 8888
  type: LoadBalancer
