apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: atonixcorp-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Memcached is the Schema for the memcacheds API
      displayName: Memcached
      kind: Memcached
      name: memcacheds.cache.atonixcorp.com
      version: v1alpha1
  description: AtonixCorp is a forward-thinking technology company specializing in
    cutting-edge data analytics solutions, security research, and innovative software
    development. Our mission is to harness the transformative power of data and technology
    to empower organizations across industries such as agriculture, energy, and healthcare.
    By leveraging advanced methodologies like machine learning, predictive analytics,
    and cloud computing, we aim to optimize operations, enhance user experiences,
    and unlock new opportunities. At AtonixCorp, we believe in the power of collaboration
    and continuous learning to drive meaningful change and push the boundaries of
    innovation.
  displayName: atonixcorpvm
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - '- Data Analytics'
  links:
  - name: Atonixcorp Operator
    url: https://atonixcorp-operator.domain
  maturity: alpha
  provider:
    name: atonixcorp
    url: https://atonixcorp.com
  version: 0.0.0
