[package]
name = "atonixcorpctl"
version = "0.1.0"
edition = "2021"

[dependencies]
ctrlc = "3.4"
clap = "4"
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }