version: 2
updates:
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: weekly
    name: Dev Container Build and Run Action
    uses: devcontainers/ci@v0.3.1900000417