

image: hashicorp/terraform

pipelines:
  default:
    - parallel:
        - step:
            name: Test
            runs-on:
              - self.hosted
              - linux
            script:
              - terraform init
              - terraform validate
        - step:
            name: Security Scan
            runs-on:
              - self.hosted
              - linux
            script:
              - pipe: atlassian/git-secrets-scan:0.5.1

  branches:
    master:
      - step:
          name: Security Scan
          runs-on:
            - self.hosted
            - linux
          script:
            - pipe: atlassian/git-secrets-scan:0.5.1
      - step:
          name: Deploy to Production
          deployment: Production
          trigger: manual
          runs-on:
            - self.hosted
            - linux
          script:
            - terraform init
            - terraform plan
            - terraform apply -auto-approve