apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"quetzal"},"name":"quetzal-deployment","namespace":"atonixcorpvm"},"spec":{"replicas":2,"selector":{"matchLabels":{"app":"quetzal"}},"template":{"metadata":{"labels":{"app":"quetzal"}},"spec":{"containers":[{"env":[{"name":"DB_HOST","value":"atonixcorpvm-postgresql"},{"name":"DB_PORT","value":"5432"},{"name":"DB_URL","value":"postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(POSTGRES_DB)"}],"envFrom":[{"secretRef":{"name":"db-credentials"}}],"image":"ofidohubvm/quetzal:latest","livenessProbe":{"httpGet":{"path":"/healthz","port":59876},"initialDelaySeconds":5,"periodSeconds":10},"name":"quetzal-container","ports":[{"containerPort":59876}],"readinessProbe":{"httpGet":{"path":"/readyz","port":59876},"initialDelaySeconds":3,"periodSeconds":5},"resources":{"limits":{"cpu":"1","memory":"1Gi"},"requests":{"cpu":"500m","memory":"512Mi"}}},{"image":"fluent/fluentd-kubernetes-daemonset:v1","name":"fluentd-cloud-logging","resources":{"limits":{"cpu":"100m","memory":"200Mi"}}}],"imagePullSecrets":[{"name":"docker-pull-secret"}]}}}}
  creationTimestamp: "2025-04-17T11:15:12Z"
  generation: 1
  labels:
    app: quetzal
  name: quetzal-deployment
  namespace: atonixcorpvm
  resourceVersion: "16948"
  uid: 37459f29-815f-4e8d-9d67-13ef06374cbe
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: quetzal
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp:  "2025-04-17T12:34:56Z"

      labels:
        app: quetzal
    spec:
      containers:
      - env:
        - name: DB_HOST
          value: atonixcorpvm-postgresql
        - name: DB_PORT
          value: "5432"
        - name: DB_URL
          value: postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(POSTGRES_DB)
        envFrom:
        - secretRef:
            name: db-credentials
        image: ofidohubvm/quetzal:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 59876
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: quetzal-container
        ports:
        - containerPort: 59876
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readyz
            port: 59876
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - image: fluent/fluentd-kubernetes-daemonset:v1
        imagePullPolicy: IfNotPresent
        name: fluentd-cloud-logging
        resources:
          requests:
            cpu: 1000m
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: docker-pull-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2025-04-17T11:15:12Z"
    lastUpdateTime: "2025-04-17T11:15:12Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2025-04-17T11:15:12Z"
    lastUpdateTime: "2025-04-17T11:15:12Z"
    message: ReplicaSet "quetzal-deployment-7684898b4d" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 1
  replicas: 2
  unavailableReplicas: 2
  updatedReplicas: 2
