version: '3.8'
services:

  quetzal:
    image: ofidohubvm/quetzal:latest
    container_name: atonixcorpvm
    ports:
      - "59876:59876"  
    env_file:
      - .env  # Load environment variables from the .env file
    volumes:
      - ./local/share/container/storage:/root/.local/share/container/storage
    depends_on:
      - quetzal_db

  db:
    image: docker.io/library/mysql:8.0
    container_name: atonixinsightdb
    env_file:
      - .env  # Load environment variables from the .env file
    ports:
      - "3307:3307"

  quetzal_db:
    image: docker.io/library/postgres:latest
    container_name: quetzal_db
    env_file:
      - .env  # Load environment variables from the .env file
    ports:
      - "5433:5433"  # Docker Compose file for setting up Quetzal and its dependencies