services:
  frontend:
    image: ofidohubvm/pixelflow:latest
    container_name: pixelflow
    environment:
      BACKEND_URL: http://172.31.74.66:5567
      PORT: 3030
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3030:3030"
    depends_on:
      - backend

  backend:
    image: ofidohubvm/vertexops:latest
    container_name: vertexops
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_PORT: 3307
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
    depends_on:
      - db

  quetzal:
    image: ofidohubvm/quetzal:latest
    container_name: atonixcorpvm
    ports:
      - "59876:59876"
    env_file:
      - .env
    volumes:
      - ./local/share/container/storage:/root/.local/share/container/storage
    depends_on:
      - quetzal_db

  quetzal_db:
    image: postgres:latest
    container_name: quetzalpostgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST_AUTH_METHOD: trust
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init.sql:/docker-entrypoint-initdb.d/init.sql

  db:
    image: mysql:8.0
    container_name: quetzalmysql_db
    env_file:
      - .env
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
    driver: local
  mysql_data:
    driver: local