version: '3.8'
services:

  quetzal:
    image: ofidohubvm/quetzal:latest
    container_name: atonixcorpvm
    ports:
      - "59876:59876"  
    environment:
      QUETZAL_ENV_VAR1: value1
      QUETZAL_ENV_VAR2: value2
    volumes:
      - ./local/share/container/storage:/root/.local/share/container/storage
    depends_on:
      - quetzal_db

  db:
    image: docker.io/library/mysql:8.0
    container_name: atonixinsightdb
    environment:
      MYSQL_ROOT_PASSWORD: sf9x7ha2tcinn
      MYSQL_DATABASE: atonixcorpinsightdb
    ports:
      - "3307:3307"

  quetzal_db:
    image: docker.io/library/postgres:latest
    container_name: quetzal_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: sf9x7ha2tcinn
      POSTGRES_DB: atonixcorpquetzaldb
    ports:
      - "5433:5433"