version: '3.8'
<<<<<<< HEAD

services:
  frontend:
    image: ofidohubvm/pixelflow:latest
    container_name: pixelflow
    environment:
      BACKEND_URL: http://172.31.74.66:5567
      PORT: 3000
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    image: ofidohubvm/vertexops:latest
    container_name: vertexops
    ports:
      - "5567:5567"
    environment:
      DB_HOST: mysql_db
      DB_PORT: 3307
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
    depends_on:
      - mysql_db

  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    env_file:
      - .env
    ports:
      - "3307:3307"
=======
>>>>>>> d8444c48 (commit 1234567890abcdef1234567890abcdef12345678)

services:
  quetzal:
    image: ofidohubvm/quetzal:latest
    container_name: atonixcorpvm
    ports:
      - "59876:59876"
    env_file:
      - .env
    volumes:
      - ./local/share/container/storage:/root/.local/share/container/storage
    depends_on:
      - quetzal_db
<<<<<<< HEAD
=======
      - db
>>>>>>> d8444c48 (commit 1234567890abcdef1234567890abcdef12345678)

  quetzal_db:
    image: postgres:latest
    container_name: quetzal_db
    env_file:
      - .env
    ports:
<<<<<<< HEAD
      - "5433:5433"
=======
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init.sql:/docker-entrypoint-initdb.d/init.sql

  db:
    image: mysql:8.0
    container_name: quetzal_db
    env_file:
      - .env
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
    driver: local
  mysql_data:
    driver: local
>>>>>>> d8444c48 (commit 1234567890abcdef1234567890abcdef12345678)
