apiVersion: v1
kind: Pod
metadata:
  generateName: quetzal-deployment-
  labels:
    app: quetzal
    pod-template-hash: 7684898b4d
  name: quetzal-deployment-7684898b4d-66w69
  namespace: atonixcorpvm
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: quetzal-deployment-7684898b4d
    uid: 31ce5835-8972-4c68-9d02-2815dfc7fab3
  resourceVersion: "16933"
  uid: be81405d-84cd-4595-acce-3b7a2cd4b597

spec:
  containers:
  - name: quetzal-container
    image: ofidohubvm/quetzal:latest
    imagePullPolicy: Always
    env:
    - name: DB_HOST
      value: atonixcorpvm-postgresql
    - name: DB_PORT
      value: "5432"
    - name: DB_URL
      value: postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(POSTGRES_DB)
    envFrom:
    - secretRef:
        name: db-credentials
    ports:
    - containerPort: 59876
      protocol: TCP
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 512Mi
    livenessProbe:
      httpGet:
        path: /healthz
        port: 59876
        scheme: HTTP
      initialDelaySeconds: 5
      periodSeconds: 10
      successThreshold: 1
      failureThreshold: 3
      timeoutSeconds: 1
    readinessProbe:
      httpGet:
        path: /readyz
        port: 59876
        scheme: HTTP
      initialDelaySeconds: 3
      periodSeconds: 5
      successThreshold: 1
      failureThreshold: 3
      timeoutSeconds: 1
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access
      readOnly: true

  - name: fluentd-cloud-logging
    image: fluent/fluentd-kubernetes-daemonset:v1
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 100m
        memory: 200Mi
      requests:
        cpu: 100m
        memory: 200Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access
      readOnly: true

  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: docker-pull-secret
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - key: "node.kubernetes.io/not-ready"
    operator: "Exists"
    effect: "NoExecute"
    tolerationSeconds: 300
  - key: "node.kubernetes.io/unreachable"
    operator: "Exists"
    effect: "NoExecute"
    tolerationSeconds: 300

  volumes:
  - name: kube-api-access
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          name: kube-root-ca.crt
          items:
          - key: ca.crt
            path: ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace

status:
  conditions:
  - lastTransitionTime: "2025-04-17T11:15:12Z"
    message: '0/1 nodes are available: 1 node(s) had untolerated taint {node.kubernetes.io/not-ready: }.'
    reason: Unschedulable
    status: "False"
    type: PodScheduled
  phase: Pending
  qosClass: Burstable