apiVersion: v1
kind: Pod
metadata:
  generateName: pixelflow-deployment-
  labels:
    app: pixelflow
    pod-template-hash: 6c6bcd46c
  name: pixelflow-deployment-6c6bcd46c-zcb7l
  namespace: atonixcorpvm
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: pixelflow-deployment-6c6bcd46c
    uid: 5c0a7c36-a623-4238-b78b-5e68fafd15df
  resourceVersion: "17293"
  uid: 00804b20-a7bd-4766-b41b-f52ac13f0aa1
spec:
  containers:
  - name: pixelflow
    image: ofidohubvm/pixelflow:latest
    imagePullPolicy: Always
    env:
    - name: BACKEND_URL
      value: http://172.31.74.66:5567
    ports:
    - containerPort: 3000
      protocol: TCP
    resources:
      limits:
        cpu: "500m"
        memory: "256Mi"
      requests:
        cpu: "250m"
        memory: "128Mi"
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access
      readOnly: true

  - name: fluentd-cloud-logging
    image: fluent/fluentd-kubernetes-daemonset:v1
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 100m
        memory: 200Mi
      requests:
        cpu: 100m
        memory: 200Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access
      readOnly: true

  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: docker-pull-secret
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - key: "node.kubernetes.io/not-ready"
    operator: "Exists"
  - key: "node.kubernetes.io/unreachable"
    operator: "Exists"
  volumes:
  - name: kube-api-access
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace

status:
  conditions:
  - lastTransitionTime: "2025-04-17T11:17:21Z"
    message: '0/1 nodes are available: 1 node(s) had untolerated taint {node.kubernetes.io/not-ready: }.'
    reason: Unschedulable
    status: "False"
    type: PodScheduled
  phase: Pending
  qosClass: Burstable