apiVersion: apps/v1
kind: Deployment
metadata:
  name: vertexops-deployment
  namespace: atonixcorpvm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vertexops
  template:
    metadata:
      labels:
        app: vertexops
    spec:
      initContainers:
      - name: check-quetzal-db
        image: busybox
        command:
          - 'sh'
          - '-c'
          - 'until nc -zv $QUETZAL_DB_HOST $QUETZAL_DB_PORT; do sleep 2; done'
      containers:
      - name: vertexops
        image: ofidohubvm/vertexops:latest
        ports:
        - containerPort: 8000
        env:
        - name: QUETZAL_DB_HOST
          value: "atonixcorpvm-postgresql"
        - name: QUETZAL_DB_PORT
          value: "5432"
        - name: QUETZAL_DB_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_USER
        - name: QUETZAL_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_PASSWORD
        - name: QUETZAL_DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_DB
        - name: QUETZAL_API_URL
          value: "http://quetzal-service.atonixcorpvm.svc.cluster.local:59876"
      imagePullSecrets:
      - name: ofidohubvm-pull-secret
---
apiVersion: v1
kind: Service
metadata:
  name: vertexops-service
  namespace: atonixcorpvm
spec:
  selector:
    app: vertexops
  ports:
  - protocol: TCP
    port: 5567
    targetPort: 8000
  type: LoadBalancer