apiVersion: apps/v1
kind: Deployment
metadata:
  name: atonixinsight-deployments
  namespace: atonixcorpvm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: atonixinsight
  template:
    metadata:
      labels:
        app: atonixinsight
    spec:
      containers:
      - name: atonixinsight
        image: ofidohubvm/atonixinsight:latest
        ports:
        - containerPort: 5678
        env:
        - name: DB_HOST
          value: "db"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          value: "sf9x7ha2tcinn"
        - name: DB_NAME
          value: "atonixcorpinsightdb"
      - name: server
        image: nginx:latest  # Example server container using NGINX
        ports:
        - containerPort: 80
        env:
        - name: SERVER_ENV
          value: "production"
      imagePullSecrets:
      - name: ofidohubvm-pull-secret