apiVersion: apps/v1
kind: Deployment
metadata:
  name: pixelflow
  namespace: atonixcorpvm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pixelflow
  template:
    metadata:
      labels:
        app: pixelflow
    spec:
      imagePullSecrets:
        - name: docker-pull-secret
      containers:
      - name: pixelflow
        image: docker.io/ofidohubvm/pixelflow:latest
        ports:
        - containerPort: 3030
        env:
        - name: BACKEND_URL
          value: "http://vertexops-service.atonixcorpvm.svc.cluster.local:5567"