apiVersion: v1
kind: Namespace
metadata:
  name: atonixcorpvm
---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: atonixcorpvm
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=  # Base64 encoded value: "postgres"
  POSTGRES_PASSWORD: c2Y5eDdoYTJ0Y2lubg==  # Base64 encoded password
  POSTGRES_DB: cXVldHphbF9kYg==  # Base64 encoded value: "quetzal_db"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quetzal-deployment
  namespace: atonixcorpvm
  labels:
    app: quetzal
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quetzal
  template:
    metadata:
      labels:
        app: quetzal
    spec:
      imagePullSecrets:
      - name: ofidohubvm-pull-secret
      containers:
      - name: quetzal-container
        image: ofidohubvm/quetzal:latest
        ports:
        - containerPort: 59876
        envFrom:
        - secretRef:
            name: db-credentials
        env:
        - name: DB_HOST
          value: "atonixcorpvm-postgresql"
        - name: DB_PORT
          value: "5432"
        - name: DB_URL
          value: "postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(POSTGRES_DB)"
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1"
            memory: "1Gi"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 59876
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readyz
            port: 59876
          initialDelaySeconds: 3
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: quetzal-service
  namespace: atonixcorpvm
spec:
  selector:
    app: quetzal
  ports:
  - name: http
    protocol: TCP
    port: 59876
    targetPort: 59876
  - name: jupyter
    protocol: TCP
    port: 8888
    targetPort: 8888
  type: ClusterIP