apiVersion: v1
kind: Namespace
metadata:
  name: atonixcorpvm
---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: atonixcorpvm
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=  # Base64 encoded username
  POSTGRES_HOST: YXRvbml4Y29ycHZtLXBvc3Rncg==  # Base64 encoded hostname
  POSTGRES_PORT: NTQzMg==  # Base64 encoded port
  POSTGRES_PASSWORD: c2Y5eDdoYTJ0Y2lubg==  # Base64 encoded password
  POSTGRES_DB: cXVldHphbF9kYg==  # Base64 encoded value for DB
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: atonixcorpvm-cloud-controller-manager
  namespace: kube-system  
  labels:
    app.kubernetes.io/name: atonixcorpvm-cloud-controller-manager
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: atonixcorpvm-cloud-controller-manager
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: atonixcorpvm-cloud-controller-manager
      annotations:
        kubernetes.io/description: atonixcorpvm Cloud controller manager for my infrastructure
    spec:
      containers:
      - name: atonixcorpvm-cloud-controller-manager
        command:
        - /bin/atonixcorpvm-cloud-controller-manager
        - --leader-elect=true
        - -v=1
        image: ofidohubvm/quetzal:latest
        resources:
          requests:
            cpu: "200m"
            memory: "50Mi"
      hostNetwork: true
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: "kubernetes.io/hostname"
            labelSelector:
              matchLabels:
                app.kubernetes.io/name: atonixcorpvm-cloud-controller-manager
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      - effect: NoExecute
        key: node.kubernetes.io/unreachable
        operator: Exists
        tolerationSeconds: 120
      - effect: NoExecute
        key: node.kubernetes.io/not-ready
        operator: Exists
        tolerationSeconds: 120
      - effect: NoSchedule
        key: node.cloudprovider.kubernetes.io/uninitialized
        operator: Exists
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quetzal-deployment
  namespace: atonixcorpvm
  labels:
    app: quetzal
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quetzal
  template:
    metadata:
      labels:
        app: quetzal
    spec:
      imagePullSecrets:
      - name: docker-pull-secret
      containers:
      - name: quetzal-container
        image: ofidohubvm/quetzal:latest
        ports:
        - containerPort: 59876
        envFrom:
        - secretRef:
            name: db-credentials
        env:
        - name: DB_HOST
          value: "atonixcorpvm-postgresql"
        - name: DB_PORT
          value: "5432"
        - name: DB_URL
          value: "postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(POSTGRES_DB)"
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1"
            memory: "1Gi"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 59876
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readyz
            port: 59876
          initialDelaySeconds: 3
          periodSeconds: 5
      - name: fluentd-cloud-logging
        image: fluent/fluentd-kubernetes-daemonset:v1
        resources:
          limits:
            cpu: "100m"
            memory: "200Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: quetzal-service
  namespace: atonixcorpvm
spec:
  selector:
    app: quetzal
  ports:
  - name: http
    protocol: TCP
    port: 59876
    targetPort: 59876
  - name: jupyter
    protocol: TCP
    port: 8888
    targetPort: 8888
  type: ClusterIP