apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: atonixcorp-tls
  namespace: atonixcorpvm
spec:
  secretName: atonixcorp-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - atonixcorp.org
    - www.atonixcorp.org
  duration: 2160h # 90 days
  renewBefore: 168h # 7 days
  usages:
    - server auth
    - client auth
    