apiVersion: apps/v1
kind: Deployment
metadata:
  name: vertexops-deployment
  namespace: atonixcorpvm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vertexops
  template:
    metadata:
      labels:
        app: vertexops
    spec:
      initContainers:
      - name: check-quetzal-db
        image: busybox
        command:
        - 'sh'
        - '-c'
        - 'until nc -zv $QUETZAL_DB_HOST $QUETZAL_DB_PORT; do sleep 2; done'
        env:
        - name: QUETZAL_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: DB_HOST
        - name: QUETZAL_DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: DB_PORT

      containers:
      - name: vertexops
        image: ofidohubvm/vertexops:latest
        ports:
        - containerPort: 5567
        env:
        - name: atonixcorp
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: DB_HOST
        - name: QUETZAL_DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: DB_PORT
        - name: QUETZAL_DB_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_USER
        - name: QUETZAL_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_PASSWORD
        - name: QUETZAL_DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_DB
        - name: QUETZAL_API_URL
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: QUETZAL_API_URL

      - name: fluentd-cloud-logging
        image: fluent/fluentd-kubernetes-daemonset:v1
        resources:
          limits:
            cpu: "100m"
            memory: "200Mi"

      imagePullSecrets:
      - name: docker-pull-secret

---
apiVersion: v1
kind: Service
metadata:
  name: vertexops-service
  namespace: atonixcorpvm
spec:
  selector:
    app: vertexops
  ports:
  - protocol: TCP
    port: 5567
    targetPort: 5567
  type: LoadBalancer