apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: atonixcorpvm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vertexops
  namespace: atonixcorpvm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vertexops
  template:
    metadata:
      labels:
        app: vertexops
    spec:
      imagePullSecrets:
        - name: docker-pull-secret
      containers:
      - name: vertexops
        image: docker.io/ofidohubvm/vertexops:latest
        ports:
        - containerPort: 5567
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "F?*RTAGl6"
        - name: MYSQL_DATABASE
          value: "quetzal_db"
        - name: MYSQL_USER
          value: "atonixdevmaster"
        - name: MYSQL_PASSWORD
          value: "F?*rtagL7dfatiFDH"
        - name: MYSQL_HOST
          value: "localhost"
        - name: MYSQL_PORT
          value: "3306"
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-storage
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: vertexops-service
  namespace: atonixcorpvm
spec:
  selector:
    app: vertexops
  ports:
    - protocol: TCP
      port: 5567
      targetPort: 5567
  type: ClusterIP