apiVersion: apps/v1
kind: Deployment
metadata:
  name: vertexops-deployments
  namespace: atonixcorpvm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vertexops
  template:
    metadata:
      labels:
        app: vertexops
    spec:
      containers:
      - name: vertexops
        image: ofidohubvm/vertexops:latest
        ports:
        - containerPort: 5678
        env:
        - name: DB_HOST
          value: "db"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          value: "sf9x7ha2tcinn"
        - name: DB_NAME
          value: "atonixcorpinsightdb"
      imagePullSecrets:
      - name: ofidohubvm-pull-secret
---
apiVersion: v1
kind: Service
metadata:
  name: vertexops-service
  namespace: atonixcorpvm
spec:
  selector:
    app: vertexops
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: LoadBalancer
