apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: atonixcorp-operator
  name: atonixcorp-operator-memcached-viewer-role
rules:
- apiGroups:
  - cache.atonixcorp.com
  resources:
  - memcacheds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.atonixcorp.com
  resources:
  - memcacheds/status
  verbs:
  - get
