apiVersion: v1
kind: Service
metadata:
  name: atonixcorp-backend-service
  namespace: atonixcorpvm
spec:
  selector:
    app: atonixcorp-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP