apiVersion: v1
kind: Service
metadata:
  name: atonixcorp-frontend
  namespace: atonixcorpvm
  labels:
    app.kubernetes.io/name: atonixcorp-frontend
    app.kubernetes.io/component: frontend
    app.kubernetes.io/instance: production
    app.kubernetes.io/managed-by: atonixcorp-operator
    app.kubernetes.io/version: "1.0.0"
  annotations:
    telemetry.istio.io/stack: "atonixcorp"
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: atonixcorp-frontend
  ports:
    - protocol: TCP
      port: 8080
      name: http
      targetPort: 3000
  type: ClusterIP