version: '3.8'

services:
  frontend:
    image: ofidohubvm/pixelflow:latest
    container_name: pixelflow
    environment:
      - NODE_ENV=production
      - API_URL=http://localhost:5678
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    image: ofidohubvm/vertexops:latest
    container_name: vertexops
    ports:
      - "5678:8000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: root
      DB_PASSWORD: sf9x7ha2tcinn
      DB_NAME: vertexopsdb
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: atonixdevdb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: sf9x7ha2tcinn
      POSTGRES_DB: vertexopsdb