apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: host-access-ingress
  namespace: default
spec:
  rules:
  - host: host-access.atonixcorp.org
    http:
      paths:
      - path: /host
        pathType: Prefix
        backend:
          service:
            name: host-access-service
            port:
              number: 8080
