name: Deploy PixelFlow Frontend to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd Workshop/PixelFlow
          npm install

      - name: Build React app
        run: |
          cd Workshop/PixelFlow
          npm run build

      - name: Upload build folder as artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: github-pages
          path: Workshop/PixelFlow/build/

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: github-pages
          path: ./build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build