name: Multi-Service Docker Build & Push

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: self-hosted  
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.io

      - name: Build and Push Pixelflow (React)
        uses: docker/build-push-action@v5
        with:
          context: ./home/Workshop/prod-dashbord/Frontend
          file: ./home/Workshop/prod-dashbord/Frontend/Dockerfile
          push: true
          tags: atonixdev/pixelflow:latest

      - name: Build and Push VertexOps (Django)
        uses: docker/build-push-action@v5
        with:
          context: ./home/Workshop/prod-dashbord/Backend
          file: ./home/Workshop/prod-dashbord/Backend/Dockerfile
          push: true
          tags: atonixdev/vertexops:latest